Snacks.zen()
vim.schedule(function()
    vim.cmd.normal({ args = { "L" }, bang = true })
end)
pcall(vim.keymap.del, "n", "q", { buffer = true })
vim.keymap.set("n", "q", function()
    Snacks.zen()
    vim.cmd("quit")
end, { buffer = true, silent = true })
