[[language]]
name = "java"
language-servers = ["jdtls"]

[language-server.jdtls]
command = "jdtls"
args = []

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }

[[language]]
name = "python"
language-id = "python"
roots = ["pyproject.toml", ".git", ".jj", ".venv/"]
language-servers = ["ruff", "basedpyright"]
auto-format = true
formatter = { command = "uvx", args = ["ruff","format", "-" ] }
file-types = ["py", "ipynb"]
comment-token = "#"
shebangs = ["python"]

[language-server.basedpyright]
command = 'uvx'
args = ['--from', 'basedpyright', 'basedpyright-langserver', "--stdio"]

[language-server.ruff]
command = "uvx"
args = ["ruff","server"]
environment = { "RUFF_TRACE" = "messages" }
