palette = "luna"

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration
$python\
$character
"""

[palettes.luna]
black = "#000000"
red = "#e08585"
green = "#6fbe80"
yellow = "#c2916a"
blue = "#75a1c7"
purple = "#c4a8d6"
cyan = "#75a1c7"
white = "#c7c7c7"
bright-black = "#888888"
bright-red = "#e08585"
bright-green = "#6fbe80"
bright-yellow = "#d9a35a"
bright-blue = "#8c9cb8"
bright-purple = "#c4a8d6"
bright-cyan = "#75a1c7"
bright-white = "#ffffff"

[fill]
symbol = " "

[directory]
style = "blue"
truncation_length = 2
truncate_to_repo = true
truncation_symbol = "…/"
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[λ](bright-yellow)"
error_symbol = "[λ](red)"
vimcmd_symbol = "[λ](bright-yellow)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "bright-yellow"

[python]
format = '[($virtualenv) ]($style)'
style = "bright-black"
