[colors]
ansi = [
  '#665c54', # overlay0
  '#ff6960', # red
  '#b0d080', # green
  '#f9bd69', # yellow
  '#89a0e0', # blue
  '#df95cf', # mauve
  '#a0d0c0', # sky
  '#d5c4a1', # subtext1
]
background = '#151515' # base
brights = [
  '#928374', # overlay2
  '#f98080', # maroon
  '#a0dfa0', # teal
  '#f9bd69', # yellow
  '#a990c9', # lavender
  '#ffa9c9', # pink
  '#95b9d0', # sapphire
  '#e0d0b0', # text
]
compose_cursor = '#ff9f9a' # flamingo
cursor_bg = '#f9bd69' # yellow
cursor_border = '#f9bd69' # yellow
cursor_fg = '#080808' # crust
foreground = '#e0d0b0' # text
scrollbar_thumb = '#928374' # overlay2
selection_bg = '#928374' # overlay2
selection_fg = '#e0d0b0' # text
split = '#7c6f64' # overlay1
visual_bell = '#3a3634' # surface1

[colors.indexed]
16 = '#f9905f' # peach
17 = '#ffc9c9' # rosewater

[colors.tab_bar]
background = '#0e0e0e'        # mantle
inactive_tab_edge = '#3a3634' # surface1

[colors.tab_bar.active_tab]
bg_color = '#df95cf'  # mauve
fg_color = '#080808'  # crust
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#252525'  # surface0
fg_color = '#e0d0b0'  # text
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#3a3634'  # surface1
fg_color = '#e0d0b0'  # text
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#504844'  # surface2
fg_color = '#e0d0b0'  # text
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#665c54'  # overlay0
fg_color = '#e0d0b0'  # text
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = ''
name = 'catppuccin-macchiato'
