FROM ubuntu:latest

# Set non-interactive mode for apt-get (to avoid prompts)
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
  apt-get install -y sudo neofetch && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN mkdir /root/dotfiles
WORKDIR /root/dotfiles
COPY . /root/dotfiles

RUN chmod +x /root/dotfiles/bootstrap.sh && \
  /root/dotfiles/bootstrap.sh

CMD ["/usr/bin/zsh"]
