# Start from the latest Arch Linux base image
FROM archlinux:latest

# Update and install sudo and core utilities
RUN pacman -Syu --noconfirm \
  sudo \
  coreutils \
  curl \
  && yes | pacman -Scc

RUN mkdir /root/dotfiles
WORKDIR /root/dotfiles
COPY . /root/dotfiles

RUN chmod +x /root/dotfiles/bootstrap.sh
ENTRYPOINT ["/root/dotfiles/bootstrap.sh"]
